import Head from 'next/head'
import Nav from './navC'
import Vid from './vidplayer'
import Slider from './slider'
import Cont from './footer'
import Cont1 from './container1'
import Cont2 from './container2'
import Container from '@mui/material/Container'
import Reviews from './reviews'
import {useEffect, useState} from 'react'


export async function getServerSideProps() {

    const userRequest = await fetch('http://localhost:8080/api/customers');
    const userData = await userRequest.json();
    return {
        props: {
            items: userData,
        }
    };

}


export default function Home(props) {

    return (
        <>
            <Head>
                <title>Magar Munchh | Order Online For Delivery</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='slider-vid-container'>
                <Vid />
                <Slider/>
            </div>
            <div className='main-container'>
                <Container maxWidth="xl">
                    <Nav customers={props}/>
                </Container>
                <Cont1 />
                <Cont2 />
                <Cont/>
            </div>
        </>
    )
}
